freinds=[]
freinds.append('Salim')
freinds.append("Laziz")
freinds.append('Jamol')
freinds.append('Hikmat')
freinds.append('Ravshan')
print(freinds)
freinds.remove("Laziz")
freinds.remove("Jamol")
print(freinds)
freinds.append("Mahmud")
freinds.append("Nosir")
freinds.insert(0, "Olim")
freinds.insert(-3, "Qobil")
print(freinds)
mehmonlar=[]
mehmonlar.append(freinds.pop(0))
mehmonlar.append(freinds.pop(3))
print(mehmonlar)